name: 'NPM Custom Action'
description: 'Installing and Caching NPM packages'
inputs:
  path-of-folder:
    desciption: 'the path to cache'
    required: true
runs:
  using: "composite"
  steps:
      - name: Cache NPM Dependencies
        uses: actions/cache@v3	
        with:
          path: ${{ inputs.path-of-folder }}	# must match where npm really installs dependencies, uses an input for the custom action
          key: ${{ runner.os }}-node-modules-${{ hashFiles('package-lock.json') }}

      - name: Install Dependencies
        run: npm install