name: Solar System Workflow

on:
      workflow_dispatch:
      push:
        branches:
            - main
            - 'feature/*'

env:
    MONGO_URI: 'mongodb+srv://supercluster.d83jj.mongodb.net/superData'
    MONGO_USERNAME: ${{ vars.MONGO_USERNAME }}
    MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}

jobs:
    unit-testing:
        strategy:
          matrix:
            nodejs_version: [18, 19, 20]
            operating_system: [ubuntu-latest, macos-latest]
            exclude:
            - nodejs_version: 18
              operating_system: macos-latest
        name: Unit Testing
        runs-on: ${{ matrix.operating_system }}
        steps:
        - name: Checkout Repository
          uses: actions/checkout@v4

        - name: Setup NodeJS Version - 18
          uses: actions/setup-node@v3
          with:
            node-version: ${{ matrix.nodejs_version }}

        - name: Install Dependencies
          run: npm install

        - name: Unit Testing
          id: nodejs-testing
          run: npm test

        - name: Archive Test Result
          uses: actions/upload-artifact@v4
          if: always()
          with:
            name: Mocha-Test-Result-${{ matrix.operating_system }}.${{ matrix.nodejs_version }}
            path: test-results.xml
    code-coverage:
        name: Code Coverage
        runs-on: ubuntu-latest
        steps:
        - name: Checkout Repository
          uses: actions/checkout@v4		# checkout the repo

        - name: Setup NodeJS Version - 18
          uses: actions/setup-node@v3	# needed since the app uses NodeJS
          with:
            node-version: 18		# installs version 18

        - name: Install Dependencies
          run: npm install			# installs dependencies from package.json

        - name: Check Code Coverage
          run: npm run coverage			# run code coverage
          continue-on-error: true

        - name: Archive Code Coverage Result
          uses: actions/upload-artifact@v4
          with:
            name: Code-Coverage-Result
            path: coverage
            retention-days: 5


 
